[package]
name = "vx"
version = "0.1.0"
authors = ["jazzfool <saveuselon@gmail.com>"]
edition = "2018"

[dependencies]
reclutch = { git = "https://github.com/jazzfool/reclutch" }
glutin = "0.24"
derivative = "2.1"
thiserror = "1.0"
